# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    devstation.vm.box="bento/ubuntu-22.04"
    devstation.vm.hostname = 'docker-station'
    devstation.vm.network "private_network", ip: "192.168.56.101"
    devstation.vm.network :forwarded_port, guest: 22, host: 2222, auto_correct: true
    devstation.vm.network :forwarded_port, guest: 81, host: 8081, auto_correct: true
    devstation.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
    end
    config.vm.provision "shell", path: "docker_bootstrap.sh", privileged: "true"
    config.vm.provision "shell", path: "apache_bootstrap.sh", privileged: "true"
end