# -*- mode: ruby -*-
# vi: set ft=ruby :

# Modify the provision if needed
# Cosnider custom Apache config/project dir 


Vagrant.configure("2") do |config|
    (1..3).each do |i| # Modifty the range to change the number of the deployed VMs
        config.vm.define "dev-station-#{i}" do |devstation|
            devstation.vm.box="bento/ubuntu-22.04"
            devstation.vm.hostname = 'dev-station'
            devstation.vm.network "private_network", ip: "192.168.56.10#{i}"
            devstation.vm.network :forwarded_port, guest: 22, host: 2222, auto_correct: true
            devstation.vm.network :forwarded_port, guest: 81, host: 8081, auto_correct: true
            devstation.vm.provider :virtualbox do |vb|
                vb.memory = 2048
                vb.cpus = 2
            end
            config.vm.provision "file", source: "apache.conf", destination: "/etc/apache2/sites-available/"
            config.vm.provision "file", source: "./project", destination: "/var/www/project"
            config.vm.provision "shell", path: "docker_bootstrap.sh", privileged: "true"
            config.vm.provision "shell", path: "apache_bootstrap.sh", privileged: "true"
        end
    end
end